//go:build ignore

package main

import (
	"encoding/base64"
	"fmt"
	"io"
	"net/http"
	"os"
)

func getBase64(url string) string {
	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		panic(err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		panic(err)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()
	return base64.RawStdEncoding.EncodeToString(body)
}

type file struct {
	name string
	url  string
}

func writeFile(filename, contentType string, files []file) {
	outfile, err := os.Create(filename)
	if err != nil {
		panic(err)
	}
	defer outfile.Close()

	outfile.WriteString(`
		package static

		// ========== WARNING ==========
		//
		// This file is auto-generated by generator.go. Do not edit!
		//
		// ==============================

		import "encoding/base64"

		func init() {
			var data []byte
			var err error
	`)

	for _, file := range files {
		fmt.Fprintf(outfile, `
			data, err = base64.RawStdEncoding.DecodeString("%s")
			if err != nil {
				panic(err)
			}
			staticfiles["%s"] = staticFile{
				data:        data,
				contentType: "%s",
			}
		`, getBase64(file.url), file.name, contentType)
	}

	outfile.WriteString("}")
}

func main() {
	writeFile("js.gen.go", "text/javascript", []file{
		{"js/htmx.min.js", "https://unpkg.com/htmx.org/dist/htmx.min.js"},
		{"js/bootstrap.bundle.min.js", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"},
		{"js/morphdom-swap.js", "https://unpkg.com/htmx.org/dist/ext/morphdom-swap.js"},
		{"js/morphdom-umd.min.js", "https://cdn.jsdelivr.net/npm/morphdom@2.7.1/dist/morphdom-umd.min.js"},
	})
	writeFile("css.gen.go", "text/css", []file{
		{"css/bootstrap.min.css", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"},
		{"css/fork-awesome.min.css", "https://cdn.jsdelivr.net/npm/fork-awesome@1.2.0/css/fork-awesome.min.css"},
	})
	writeFile("fonts.gen.go", "font/woff2", []file{
		{"fonts/forkawesome-webfont.woff2", "https://cdn.jsdelivr.net/npm/fork-awesome@1.2.0/fonts/forkawesome-webfont.woff2"},
	})
}
