repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [markdown]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # black
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        files: ^(sublime_music|tests)/.*\.py$

  # isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^(sublime_music|tests)/.*\.py$

  # flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: ^(sublime_music|tests)/.*\.py$
        additional_dependencies:
          - flake8-annotations
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-pep3101
          - flake8-print

  # mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        files: ^(sublime_music|tests)/.*\.py$
        additional_dependencies:
          - types-bleach
          - types-peewee
          - types-python-dateutil
          - types-pyyaml
          - types-requests
          - types-tabulate
          - types-termcolor

  # custom style checks
  - repo: local
    hooks:
      - id: custom-style-check
        name: custom style check
        entry: ./cicd/custom_style_check.py
        language: python
        additional_dependencies:
          - termcolor==2.1.1
