// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logger} from '../models';
import {context} from '../models';

export function Logger():Promise<logger.Logger>;

export function OnDomReady(arg1:context.Context):Promise<void>;
