// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Logger() {
  return window['go']['app']['App']['Logger']();
}

export function OnDomReady(arg1) {
  return window['go']['app']['App']['OnDomReady'](arg1);
}
